#---------------------------
# Hexo Theme Fluid
# Author: Fluid-dev
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# 配置指南: https://hexo.fluid-dev.com/docs/guide/
# 你可以从指南中获得更详细的说明

# 用于浏览器标签的图标
favicon: /img/icon.png

# 用于苹果设备的图标
apple_touch_icon: /img/icon.png

# 网页访问统计
web_analytics:  # 网页访问统计
  enable: true

  # 百度统计的 Key，值需要获取下方链接中 `hm.js?` 后边的字符串
  # See: https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376
  baidu: a42297b398451c11cf9852c2dfa19253

#---------------------------
# 页头
#---------------------------

# 导航栏的相关配置
navbar:
  # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
  blog_title: 挺的记事簿

  # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    #- { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }

#---------------------------
# 首页
#---------------------------
index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  banner_img: /img/main.jpg

  # 头图高度，屏幕百分比
  # Available: 0 - 100
  banner_img_height: 70

  # 首页副标题的独立设置
  slogan:
    enable: true

    # 为空则按 hexo config.subtitle 显示
    text: "小礼札记"

#---------------------------
# 文章页
#---------------------------
post:
  banner_img: /img/default.jpg

  # 评论插件
  comments:
    enable: true
    type: valine

#---------------------------
# 评论插件
#---------------------------

# Valine
valine:
  appId: MfqMCE7bV2FERa8qRoCPLY2f-gzGzoHsz
  appKey: DtsHTEOjSeUmVFcPEUnoyEqR

#---------------------------
# 归档页
#---------------------------
archive:
  banner_img: /img/archives.jpg

#---------------------------
# 分类页
#---------------------------
category:
  enable: true
  banner_img: /img/categories.jpg

#---------------------------
# 标签页
#---------------------------
tag:
  enable: true
  banner_img: /img/tags.jpg

#---------------------------
# 关于页
#---------------------------
about:
  enable: false
  banner_img: /img/default.jpg

#---------------------------
# 自定义页
#
# 通过 hexo new page 命令创建的页面
#---------------------------
page:
  banner_img: /img/default.jpg

#---------------------------
# 404页
#---------------------------
page404:
  enable: true
  banner_img: /img/404.jpg

#---------------------------
# 友链页
#---------------------------
links:
  enable: true
  banner_img: /img/links.jpg
  # 友链的成员项
  items:
    - {
      title: 'Github',
      link: 'https://github.com/TING2938',
      avatar: '/img/github.svg'
    }
    - {
      title: 'Hexo Theme Fluid',
      link: 'https://hexo.fluid-dev.com/',
      avatar: '/img/favicon.png'
    }
    - {
      title: 'Lu Tian',
      link: 'http://www.keinsci.com/members/Tian_Lu.shtml'
    }
